package com.example.ui.util

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    ARABIC("ar", "العربية")
}

object StringResources {
    fun getString(key: String, language: AppLanguage): String {
        val isAr = language == AppLanguage.ARABIC
        return when (key) {
            "app_title" -> "SaveFlow"
            "app_subtitle" -> if (isAr) "مُحمّل الفيديوهات الشامل والفاخر" else "Universal Video & Reels Downloader"
            "hero_title" -> if (isAr) "حمّل أي فيديو. بكل سهولة." else "Download Anything. Effortlessly."
            "hero_subtitle" -> if (isAr) "احفظ الفيديوهات القصيرة من جميع منصاتك المفضلة." else "Save your favorite videos from your favorite platforms."
            "input_hint" -> if (isAr) "الصق رابط الفيديو هنا..." else "Paste video link..."
            "paste_button" -> if (isAr) "لصق" else "Paste"
            "clear_button" -> if (isAr) "مسح" else "Clear"
            "download_button" -> if (isAr) "تنزيل" else "Download"
            "download_video_button" -> if (isAr) "تنزيل الفيديو" else "Download Video"
            "analyzing_link" -> if (isAr) "جاري تحليل الرابط..." else "Analyzing video link..."
            "platform_detected" -> if (isAr) "تم اكتشاف المنصة" else "Platform detected"
            "quality_label" -> if (isAr) "الجودة" else "Quality"
            "format_label" -> if (isAr) "الصيغة" else "Format"
            "auto_quality" -> if (isAr) "تلقائي" else "Auto"
            "preview_title" -> if (isAr) "معاينة الفيديو" else "Video Preview"
            "cancel" -> if (isAr) "إلغاء" else "Cancel"
            "downloading" -> if (isAr) "جاري التنزيل..." else "Downloading..."
            "download_completed" -> if (isAr) "تم التنزيل بنجاح ✓" else "Downloaded ✓"
            "recent_downloads" -> if (isAr) "آخر التنزيلات" else "Recent Downloads"
            "view_all" -> if (isAr) "عرض الكل" else "View All"
            "all_downloads" -> if (isAr) "التنزيلات" else "Downloads"
            "history_title" -> if (isAr) "السجل الزمني" else "History Timeline"
            "search_hint" -> if (isAr) "بحث في التنزيلات..." else "Search downloads..."
            "no_downloads_yet" -> if (isAr) "لا توجد تنزيلات بعد" else "No downloads yet"
            "no_downloads_sub" -> if (isAr) "الصق رابط أي فيديو وابدأ التنزيل فوراً." else "Paste a video link to get started."
            "nav_home", "tab_home" -> if (isAr) "الرئيسية" else "Home"
            "nav_downloads", "tab_downloads" -> if (isAr) "التنزيلات" else "Downloads"
            "nav_history", "tab_history" -> if (isAr) "السجل" else "History"
            "nav_settings", "tab_settings" -> if (isAr) "الإعدادات" else "Settings"
            "filter_all", "tab_all" -> if (isAr) "الكل" else "All"
            "filter_videos", "tab_videos" -> if (isAr) "فيديوهات" else "Videos"
            "filter_audio", "tab_audio" -> if (isAr) "صوتيات" else "Audio"
            "time_today" -> if (isAr) "اليوم" else "Today"
            "time_yesterday" -> if (isAr) "أمس" else "Yesterday"
            "time_this_week" -> if (isAr) "هذا الأسبوع" else "This Week"
            "action_play" -> if (isAr) "تشغيل" else "Play"
            "watch_reel" -> if (isAr) "مشاهدة الريل" else "Watch Reel"
            "preview_reel" -> if (isAr) "معاينة وتشغيل الريل" else "Preview & Play Reel"
            "action_share" -> if (isAr) "مشاركة" else "Share"
            "action_save_gallery" -> if (isAr) "حفظ في المعرض" else "Save to Gallery"
            "action_copy_link" -> if (isAr) "نسخ الرابط" else "Copy Link"
            "action_open_folder" -> if (isAr) "فتح المجلد" else "Open Folder"
            "action_delete" -> if (isAr) "حذف" else "Delete"
            "action_redownload" -> if (isAr) "إعادة التنزيل" else "Download Again"
            "delete_confirm_title" -> if (isAr) "حذف الملف" else "Delete File"
            "delete_confirm_message" -> if (isAr) "هل أنت متأكد من حذف هذا الملف نهائياً؟" else "Are you sure you want to delete this file?"
            "settings_general" -> if (isAr) "عام" else "General"
            "settings_auto_paste" -> if (isAr) "لصق الروابط تلقائياً" else "Auto Paste Links"
            "settings_auto_download" -> if (isAr) "التنزيل التلقائي" else "Auto Download"
            "settings_default_quality" -> if (isAr) "الجودة الافتراضية" else "Default Quality"
            "settings_default_format" -> if (isAr) "الصيغة الافتراضية" else "Default Format"
            "settings_downloads_sec" -> if (isAr) "إعدادات التنزيل" else "Downloads"
            "settings_location" -> if (isAr) "موقع التنزيل" else "Download Location"
            "settings_wifi_only" -> if (isAr) "التنزيل عبر Wi-Fi فقط" else "Wi-Fi Only"
            "settings_simultaneous" -> if (isAr) "تنزيلات متزامنة" else "Simultaneous Downloads"
            "settings_appearance" -> if (isAr) "المظهر واللون" else "Appearance"
            "settings_theme" -> if (isAr) "النمط" else "Theme"
            "settings_accent_color" -> if (isAr) "لون التميز" else "Accent Color"
            "settings_about" -> if (isAr) "حول التطبيق" else "About"
            "settings_version" -> if (isAr) "الإصدار" else "Version"
            "settings_privacy" -> if (isAr) "سياسة الخصوصية" else "Privacy Policy"
            "settings_terms" -> if (isAr) "شروط الخدمة" else "Terms of Service"
            "settings_about_app" -> if (isAr) "عن SaveFlow" else "About SaveFlow"
            "supported_platforms" -> if (isAr) "المنصات المدعومة" else "Supported Platforms"
            "supported_platforms_sub" -> if (isAr) "اضغط على المنصة للتنزيل المباشر" else "Tap a platform for direct download"
            "in_app_player" -> if (isAr) "مشغل الفيديو الداخلي" else "In-App Player"
            "speed_label" -> if (isAr) "السرعة" else "Speed"
            "developer_label" -> if (isAr) "تطوير بواسطة" else "Developed By"
            "developer_name" -> "Youssef Mansouri"
            "app_rights" -> if (isAr) "جميع الحقوق محفوظة © Youssef Mansouri" else "© Youssef Mansouri. All rights reserved."
            "link_copied_toast" -> if (isAr) "تم نسخ الرابط بنجاح" else "Link copied to clipboard"
            "invalid_url_error" -> if (isAr) "رابط فيديو غير صالح، يرجى التأكد من الرابط" else "Invalid video URL, please verify link"
            "network_error" -> if (isAr) "خطأ في الشبكة، يرجى التحقق من اتصالك" else "Network error, check your connection"
            "unknown_error" -> if (isAr) "حدث خطأ غير متوقع" else "An unexpected error occurred"
            else -> key
        }
    }
}

